// Chinese Proverbs Collection - 200+ Proverbs
const proverbs = [
    { cn: "活到老，学到老", en: "Live until old, learn until old. / Never too old to learn." },
    { cn: "一寸光阴一寸金", en: "An inch of time is an inch of gold. / Time is precious." },
    { cn: "三思而后行", en: "Think three times before you act. / Look before you leap." },
    { cn: "熟能生巧", en: "Skill comes from practice. / Practice makes perfect." },
    { cn: "失败是成功之母", en: "Failure is the mother of success." },
    { cn: "滴水穿石", en: "Dripping water wears through stone. / Perseverance brings success." },
    { cn: "有志者事竟成", en: "Where there is a will, there is a way." },
    { cn: "不经一事，不长一智", en: "You can't gain wisdom without experience." },
    { cn: "塞翁失马，焉知非福", en: "A loss may turn out to be a gain. / Every cloud has a silver lining." },
    { cn: "一言既出，驷马难追", en: "Once spoken, words cannot be taken back." },
    { cn: "千里之行，始于足下", en: "A journey of a thousand miles begins with a single step." },
    { cn: "良药苦口利于病", en: "Good medicine tastes bitter but cures illness. / Honest advice is hard to take." },
    { cn: "青出于蓝而胜于蓝", en: "Blue comes from indigo but is deeper than indigo. / The student surpasses the master." },
    { cn: "骄者必败", en: "The proud will surely fall. / Pride comes before a fall." },
    { cn: "学而不思则罔", en: "Learning without thinking is labor lost." },
    { cn: "温故而知新", en: "Review the old to learn the new." },
    { cn: "己所不欲，勿施于人", en: "Do not do to others what you do not want done to yourself." },
    { cn: "三人行，必有我师", en: "When three walk together, there must be a teacher among them." },
    { cn: "知之为知之，不知为不知", en: "To know what you know and know what you do not know is true knowledge." },
    { cn: "工欲善其事，必先利其器", en: "To do good work, one must first sharpen one's tools." },
    { cn: "天行健，君子以自强不息", en: "As heaven maintains vigor, a gentleman strives constantly to improve himself." },
    { cn: "地势坤，君子以厚德载物", en: "As earth is receptive, a gentleman carries virtue to bear all things." },
    { cn: "满招损，谦受益", en: "Arrogance brings loss, modesty brings benefit." },
    { cn: "机不可失，时不再来", en: "Opportunity knocks but once. / Seize the moment." },
    { cn: "不入虎穴，焉得虎子", en: "If you don't enter the tiger's den, how can you catch the tiger's cub? / Nothing ventured, nothing gained." },
    { cn: "前事不忘，后事之师", en: "Remember the past to guide the future." },
    { cn: "亡羊补牢，为时未晚", en: "To mend the pen after the sheep is lost is not too late. / Better late than never." },
    { cn: "百闻不如一见", en: "Hearing something a hundred times is not as good as seeing it once." },
    { cn: "如鱼得水", en: "Like a fish in water. / In one's element." },
    { cn: "画蛇添足", en: "Draw legs on a snake. / Ruin the effect by adding something superfluous." },
    { cn: "对牛弹琴", en: "Play the lute to a cow. / Cast pearls before swine." },
    { cn: "掩耳盗铃", en: "Cover one's ears while stealing a bell. / Deceive oneself." },
    { cn: "守株待兔", en: "Watch the tree stump, waiting for a hare. / Wait for windfalls." },
    { cn: "刻舟求剑", en: "Mark the boat to find the sword. / Take measures without regard to changing circumstances." },
    { cn: "叶公好龙", en: "Lord Ye's love of dragons. / Professed love of what one really fears." },
    { cn: "自相矛盾", en: "Attack one's own shield with one's spear. / Self-contradictory." },
    { cn: "狐假虎威", en: "The fox borrows the tiger's terror. / Borrow power to bully others." },
    { cn: "井底之蛙", en: "A frog at the bottom of a well. / A person with limited outlook." },
    { cn: "杯弓蛇影", en: "See the reflection of a bow as a snake. / Extremely suspicious." },
    { cn: "草木皆兵", en: "Every bush and tree looks like an enemy. / Panic-stricken." },
    { cn: "望梅止渴", en: "Quench thirst by thinking of plums. / Console oneself with false hopes." },
    { cn: "破釜沉舟", en: "Break the cauldrons and sink the boats. / Burn one's bridges." },
    { cn: "背水一战", en: "Fight with one's back to the river. / Take a desperate stand." },
    { cn: "四面楚歌", en: "Songs of Chu on all sides. / Besieged on all sides." },
    { cn: "纸上谈兵", en: "Discuss military tactics on paper. / Armchair strategy." },
    { cn: "指鹿为马", en: "Point at a deer and call it a horse. " },
    { cn: "完璧归赵", en: "Return the jade intact to Zhao. / Return something to its owner unharmed." },
    { cn: "负荆请罪", en: "Carry thorny sticks to ask for punishment. / Offer a humble apology." },
    { cn: "卧薪尝胆", en: "Sleep on brushwood and taste gall. / Endure hardships to accomplish a goal." },
    { cn: "毛遂自荐", en: "Mao Sui recommends himself. / Volunteer one's services." },
    { cn: "纸上得来终觉浅", en: "Knowledge from books is superficial after all." },
    { cn: "山重水复疑无路", en: "Mountains multiply and streams double back, I doubt there's a road." },
    { cn: "柳暗花明又一村", en: "Willows dark, flowers bright, another village appears. / Suddenly see a hope." },
    { cn: "海内存知己", en: "Within the four seas, all men are brothers." },
    { cn: "天涯若比邻", en: "At the ends of the earth, we are as close as neighbors." },
    { cn: "欲穷千里目", en: "To see a thousand miles, ascend another story." },
    { cn: "更上一层楼", en: "Ascend another story to see further." },
    { cn: "少壮不努力", en: "If one does not work hard in youth." },
    { cn: "老大徒伤悲", en: "In old age one will grieve in vain." },
    { cn: "野火烧不尽", en: "Wildfire cannot burn it all." },
    { cn: "春风吹又生", en: "Spring wind brings it back to life." },
    { cn: "会当凌绝顶", en: "I will ascend the peak." },
    { cn: "一览众山小", en: "And see all mountains small below." },
    { cn: "问渠那得清如许", en: "How is the stream so clear?" },
    { cn: "为有源头活水来", en: "Because fresh water flows from its source." },
    { cn: "纸上得来终觉浅", en: "Knowledge from paper remains shallow." },
    { cn: "绝知此事要躬行", en: "To truly know, one must practice." },
    { cn: "不识庐山真面目", en: "I cannot see the true face of Mount Lu." },
    { cn: "只缘身在此山中", en: "Because I am standing in the midst of it." },
    { cn: "采菊东篱下", en: "Picking chrysanthemums by the eastern fence." },
    { cn: "悠然见南山", en: "Leisurely I see the southern mountain." },
    { cn: "海上升明月", en: "The bright moon rises from the sea." },
    { cn: "天涯共此时", en: "At this moment, shared at the ends of the earth." },
    { cn: "但愿人长久", en: "May we all be blessed with longevity." },
    { cn: "千里共婵娟", en: "Though far apart, we are still under the same moon." },
    { cn: "两情若是久长时", en: "If love between two is everlasting." },
    { cn: "又岂在朝朝暮暮", en: "Why need they stay together every day and night?" },
    { cn: "天生我材必有用", en: "Heaven gave me talents for a purpose." },
    { cn: "千金散尽还复来", en: "A thousand gold spent will return again." },
    { cn: "人生得意须尽欢", en: "In life's prime, enjoy to the fullest." },
    { cn: "莫使金樽空对月", en: "Do not let the golden cup face the moon in vain." },
    { cn: "长风破浪会有时", en: "A time will come to ride the wind and cleave the waves." },
    { cn: "直挂云帆济沧海", en: "With sails hoisted high, cross the vast ocean." },
    { cn: "春蚕到死丝方尽", en: "The spring silkworm spins till death." },
    { cn: "蜡炬成灰泪始干", en: "The candle burns to ashes, tears dry up." },
    { cn: "山不在高，有仙则名", en: "A mountain need not be high; if immortals dwell there, it is famous." },
    { cn: "水不在深，有龙则灵", en: "Water need not be deep; if dragons live there, it is magical." },
    { cn: "出淤泥而不染", en: "Rising from the mud unsoiled." },
    { cn: "濯清涟而不妖", en: "Washed in clear ripples yet not flamboyant." },
    { cn: "老骥伏枥，志在千里", en: "An old steed in the stable still aspires to gallop a thousand miles." },
    { cn: "烈士暮年，壮心不已", en: "A noble-hearted man in his old age never loses his ambition." },
    { cn: "先天下之忧而忧", en: "Be the first to worry about the world's troubles." },
    { cn: "后天下之乐而乐", en: "And the last to enjoy its pleasures." },
    { cn: "不以物喜，不以己悲", en: "Not pleased by external gains, not saddened by personal losses." },
    { cn: "居庙堂之高则忧其民", en: "In high office, worry about the people." },
    { cn: "处江湖之远则忧其君", en: "Far from court, worry about the sovereign." },
    { cn: "路漫漫其修远兮", en: "The road ahead is long and far." },
    { cn: "吾将上下而求索", en: "I will search high and low." },
    { cn: "亦余心之所善兮", en: "For what my heart holds dear." },
    { cn: "虽九死其犹未悔", en: "Though I die nine times, I would not regret." },
    { cn: "知我者谓我心忧", en: "Those who know me say I am sad." },
    { cn: "不知我者谓我何求", en: "Those who don't ask what I seek." },
    { cn: "一日不见，如三秋兮", en: "One day apart seems like three autumns." },
    { cn: "执子之手，与子偕老", en: "Hold your hand and grow old with you." },
    { cn: "窈窕淑女，君子好逑", en: "A graceful maiden is a gentleman's good match." },
    { cn: "关关雎鸠，在河之洲", en: "Guan guan cry the ospreys on the islet in the river." },
    { cn: "桃之夭夭，灼灼其华", en: "The peach tree is young and elegant, brilliant are its flowers." },
    { cn: "投我以桃，报之以李", en: "You throw me a peach, I give you a plum. / Return a favor." },
    { cn: "他山之石，可以攻玉", en: "Stones from another mountain can polish jade. / Advice from others helps." },
    { cn: "靡不有初，鲜克有终", en: "All things have a beginning, but few have an end." },
    { cn: "高山仰止，景行行止", en: "Look up to the high mountain, follow the great road." },
    { cn: "如切如磋，如琢如磨", en: "Cut and polish, carve and grind. / Cultivate oneself." },
    { cn: "巧笑倩兮，美目盼兮", en: "A sweet smile with dimples, beautiful eyes glancing." },
    { cn: "一日为师，终身为父", en: "One day as teacher, lifetime as father." },
    { cn: "教不严，师之惰", en: "If teaching is not strict, it is the teacher's laziness." },
    { cn: "子不学，非所宜", en: "If the child does not learn, it is not proper." },
    { cn: "幼不学，老何为", en: "If one does not learn in youth, what will one do in old age?" },
    { cn: "玉不琢，不成器", en: "Jade uncarved cannot form a vessel." },
    { cn: "人不学，不知义", en: "People without learning do not know righteousness." },
    { cn: "养不教，父之过", en: "To nurture without teaching is the father's fault." },
    { cn: "教不严，师之惰", en: "To teach without severity is the teacher's laziness." },
    { cn: "贵有恒，何必三更眠五更起", en: "What matters is persistence, not sleeping late and rising early." },
    { cn: "最无益，只怕一日曝十日寒", en: "Worst is one day of sun followed by ten days of cold." },
    { cn: "读书破万卷", en: "Read ten thousand volumes." },
    { cn: "下笔如有神", en: "Write as if guided by gods." },
    { cn: "书山有路勤为径", en: "In the mountain of books, diligence is the path." },
    { cn: "学海无涯苦作舟", en: "In the endless sea of learning, hardship is the boat." },
    { cn: "黑发不知勤学早", en: "In black hair, one does not know to study early." },
    { cn: "白首方悔读书迟", en: "With white hair, one regrets starting late." },
    { cn: "宝剑锋从磨砺出", en: "A sharp sword is forged through grinding." },
    { cn: "梅花香自苦寒来", en: "Plum blossoms are fragrant from bitter cold." },
    { cn: "只要功夫深", en: "If you work hard enough." },
    { cn: "铁杵磨成针", en: "An iron rod can be ground into a needle." },
    { cn: "世上无难事", en: "In the world, nothing is difficult." },
    { cn: "只怕有心人", en: "If you put your mind to it." },
    { cn: "吃得苦中苦", en: "Eat the bitterest of the bitter." },
    { cn: "方为人上人", en: "Become the highest of the high." },
    { cn: "不怕慢，就怕站", en: "Fear not slowness, but standing still." },
    { cn: "站得高，看得远", en: "Stand high, see far." },
    { cn: "欲速则不达", en: "Haste makes waste." },
    { cn: "瓜熟蒂落", en: "When the melon is ripe, it falls. / Things happen in their own time." },
    { cn: "水到渠成", en: "When the water comes, the channel forms. / Success comes naturally." },
    { cn: "种瓜得瓜，种豆得豆", en: "Sow melons, reap melons; sow beans, reap beans. / As you sow, so shall you reap." },
    { cn: "一分耕耘，一分收获", en: "No pain, no gain." },
    { cn: "天道酬勤", en: "Heaven rewards the diligent." },
    { cn: "勤能补拙", en: "Diligence can make up for lack of talent." },
    { cn: "笨鸟先飞", en: "The slow bird starts early. / The early bird catches the worm." },
    { cn: "早起的鸟儿有虫吃", en: "The early bird catches the worm." },
    { cn: "业精于勤，荒于嬉", en: "Excellence comes from diligence, failure from play." },
    { cn: "行成于思，毁于随", en: "Success comes from thought, failure from carelessness." },
    { cn: "学如不及，犹恐失之", en: "Learn as if you cannot catch up, fearing to lose what you have." },
    { cn: "敏而好学，不耻下问", en: "Quick and eager to learn, not ashamed to ask those below." },
    { cn: "学而不厌，诲人不倦", en: "Never tired of learning, never weary of teaching." },
    { cn: "博学之，审问之", en: "Study extensively, inquire carefully." },
    { cn: "慎思之，明辨之", en: "Think deeply, distinguish clearly." },
    { cn: "笃行之", en: "Practice sincerely." },
    { cn: "知易行难", en: "Knowing is easy, doing is hard." },
    { cn: "知行合一", en: "Unity of knowledge and action." },
    { cn: "实事求是", en: "Seek truth from facts." },
    { cn: "明察秋毫", en: "See clearly the autumn hair. / Perceptive of the smallest details." },
    { cn: "见微知著", en: "See the significant in the trivial." },
    { cn: "举一反三", en: "Infer three from one. / Draw inferences." },
    { cn: "触类旁通", en: "Understand related categories. / Grasp by analogy." },
    { cn: "循序渐进", en: "Proceed step by step." },
    { cn: "由浅入深", en: "From shallow to deep." },
    { cn: "深入浅出", en: "Explain profound simply." },
    { cn: "厚积薄发", en: "Accumulate deeply, release sparingly." },
    { cn: "博观而约取", en: "View broadly and take selectively." },
    { cn: "厚积而薄发", en: "Accumulate much, release little." },
    { cn: "取法乎上，仅得乎中", en: "Aim for the top, settle for the middle." },
    { cn: "取法乎中，仅得乎下", en: "Aim for the middle, get the bottom." },
    { cn: "不以规矩，不能成方圆", en: "Without compass and square, no circle or square. / Rules are necessary." },
    { cn: "无规矩不成方圆", en: "Without rules, nothing can be accomplished." },
    { cn: "上有政策，下有对策", en: "Above there is policy, below there is countermeasure." },
    { cn: "水能载舟，亦能覆舟", en: "Water can carry a boat, and also overturn it." },
    { cn: "得道多助，失道寡助", en: "With justice on your side, many will help; without it, few." },
    { cn: "天时不如地利", en: "Heaven's timing is not as good as earth's advantage." },
    { cn: "地利不如人和", en: "Earth's advantage is not as good as harmony among people." },
    { cn: "人心齐，泰山移", en: "When hearts unite, Mount Tai moves." },
    { cn: "众人拾柴火焰高", en: "When everyone adds firewood, the flames rise high." },
    { cn: "三个臭皮匠", en: "Three cobblers with their wits combined." },
    { cn: "赛过诸葛亮", en: "Surpass Zhuge Liang." },
    { cn: "单丝不成线", en: "A single thread does not make a line." },
    { cn: "独木不成林", en: "A single tree does not make a forest." },
    { cn: "孤掌难鸣", en: "A single palm cannot clap. / One hand cannot clap." },
    { cn: "一个好汉三个帮", en: "A good man needs three helpers." },
    { cn: "朋友多了路好走", en: "With many friends, the road is easy." },
    { cn: "近朱者赤，近墨者黑", en: "Near vermilion, one turns red; near ink, one turns black." },
    { cn: "物以类聚，人以群分", en: "Things of a kind come together, people of a mind fall into groups." },
    { cn: "酒逢知己千杯少", en: "With a close friend, a thousand cups are not enough." },
    { cn: "话不投机半句多", en: "With a stranger, half a sentence is too much." },
    { cn: "海内存知己", en: "A bosom friend afar brings a distant land near." },
    { cn: "君子之交淡如水", en: "The friendship of gentlemen is like water." },
    { cn: "小人之交甘若醴", en: "The friendship of petty men is like sweet wine." },
    { cn: "岁寒知松柏", en: "In cold winter, we know the pine and cypress." },
    { cn: "患难见真情", en: "In adversity, we see true friendship." },
    { cn: "路遥知马力", en: "Over a long distance, we know the horse's strength." },
    { cn: "日久见人心", en: "Over a long time, we see the person's heart." },
    { cn: "人心隔肚皮", en: "The heart is separated by the belly. / Hard to know what's in another's heart." },
    { cn: "害人之心不可有", en: "Do not have the heart to harm others." },
    { cn: "防人之心不可无", en: "Do not lack the heart to guard against others." },
    { cn: "忍一时风平浪静", en: "Endure a moment, and all is calm." },
    { cn: "退一步海阔天空", en: "Step back, and the sea is vast and sky is open." },
    { cn: "宰相肚里能撑船", en: "In a prime minister's stomach, a boat can sail. / Great capacity for tolerance." },
    { cn: "大人不计小人过", en: "A great man does not count a petty man's faults." },
    { cn: "得饶人处且饶人", en: "Where you can forgive, forgive." },
    { cn: "冤家宜解不宜结", en: "Enmity should be resolved, not created." },
    { cn: "和气生财", en: "Harmony brings wealth." },
    { cn: "家和万事兴", en: "When the family is harmonious, all affairs prosper." },
    { cn: "远亲不如近邻", en: "A distant relative is not as good as a near neighbor." },
    { cn: "金窝银窝不如自己的狗窝", en: "Gold nest, silver nest, not as good as one's own dog nest." },
    { cn: "子不嫌母丑", en: "A son does not think his mother ugly." },
    { cn: "狗不嫌家贫", en: "A dog does not think his home poor." },
    { cn: "父母在，不远游", en: "While parents are alive, do not travel far." },
    { cn: "游必有方", en: "If you travel, have a destination." },
    { cn: "树欲静而风不止", en: "The tree wishes to be still, but the wind will not stop." },
    { cn: "子欲养而亲不待", en: "The son wishes to care for parents, but they are gone." },
    { cn: "身体发肤，受之父母", en: "Body, hair and skin are received from parents." },
    { cn: "不敢毁伤", en: "Dare not damage them." },
    { cn: "孝当竭力", en: "Filial piety should be done with all one's might." },
    { cn: "非徒养生", en: "Not merely supporting life." },
    { cn: "百善孝为先", en: "Of all virtues, filial piety comes first." },
    { cn: "万恶淫为首", en: "Of all evils, lust comes first." },
    { cn: "精诚所至", en: "With complete sincerity." },
    { cn: "金石为开", en: "Even metal and stone will open." },
    { cn: "天下无难事", en: "In the world, nothing is difficult." },
    { cn: "只怕有心人", en: "If you put your heart into it." },
    { cn: "有志不在年高", en: "Ambition is not about age." },
    { cn: "无志空活百岁", en: "Without ambition, live a hundred years in vain." },
    { cn: "燕雀安知鸿鹄之志", en: "How can a sparrow know the ambition of a swan?" },
    { cn: "穷且益坚", en: "Though poor, become stronger." },
    { cn: "不坠青云之志", en: "Do not lose your high aspiration." },
    { cn: "生当作人杰", en: "In life, be a hero among men." },
    { cn: "死亦为鬼雄", en: "In death, be a champion among ghosts." },
    { cn: "人生自古谁无死", en: "Since ancient times, who has not died?" },
    { cn: "留取丹心照汗青", en: "Leave a loyal heart to shine in history." },
    { cn: "富贵不能淫", en: "Wealth and rank cannot corrupt." },
    { cn: "贫贱不能移", en: "Poverty and lowliness cannot shift." },
    { cn: "威武不能屈", en: "Might and force cannot bend." },
    { cn: "此之谓大丈夫", en: "This is called a true man." },
    { cn: "君子坦荡荡", en: "A gentleman is calm and peaceful." },
    { cn: "小人长戚戚", en: "A petty man is always worried." },
    { cn: "人而无信，不知其可", en: "If a man is not trustworthy, what can he do?" },
    { cn: "一言九鼎", en: "One word weighs as much as nine tripods. / Promise is weighty." },
    { cn: "一诺千金", en: "A promise is worth a thousand gold." },
    { cn: "君子一言，驷马难追", en: "A gentleman's word cannot be overtaken by four horses." },
    { cn: "言必行，行必果", en: "Words must be acted upon, actions must have results." },
    { cn: "知耻近乎勇", en: "Knowing shame is close to courage." },
    { cn: "过而能改，善莫大焉", en: "To err and then reform is the greatest good." },
    { cn: "浪子回头金不换", en: "A prodigal son returning is worth more than gold." },
    { cn: "亡羊补牢，为时未晚", en: "Mend the pen after the sheep is lost, it is not too late." },
    { cn: "前事不忘，后事之师", en: "Remember the past to guide the future." },
    { cn: "前车之覆，后车之鉴", en: "The overturned cart ahead warns the cart behind." },
    { cn: "吃一堑，长一智", en: "Fall into a pit, gain a wisdom." },
    { cn: "不经一事，不长一智", en: "Without experience, one does not gain wisdom." },
    { cn: "祸兮福之所倚", en: "Misfortune leans on fortune." },
    { cn: "福兮祸之所伏", en: "Fortune hides in misfortune." },
    { cn: "塞翁失马，焉知非福", en: "The old man lost his horse, who knows if it is a blessing?" },
    { cn: "乐极生悲", en: "Extreme joy gives rise to sorrow." },
    { cn: "否极泰来", en: "When misfortune reaches its limit, fortune comes." },
    { cn: "物极必反", en: "When things reach an extreme, they turn back." },
    { cn: "月满则亏", en: "When the moon is full, it wanes." },
    { cn: "水满则溢", en: "When water is full, it overflows." },
    { cn: "人满则骄", en: "When a man is full, he becomes arrogant." },
    { cn: "盛极必衰", en: "When prosperity reaches its peak, it declines." },
    { cn: "花无百日红", en: "Flowers are not red for a hundred days." },
    { cn: "人无千日好", en: "People are not good for a thousand days." },
    { cn: "三十年河东", en: "Thirty years on the east of the river." },
    { cn: "三十年河西", en: "Thirty years on the west of the river." },
    { cn: "江山易改", en: "Rivers and mountains are easy to change." },
    { cn: "本性难移", en: "But one's nature is hard to change." },
    { cn: "冰冻三尺", en: "Ice freezes three feet deep." },
    { cn: "非一日之寒", en: "Not from one day of cold." },
    { cn: "滴水穿石", en: "Dripping water penetrates stone." },
    { cn: "非一日之功", en: "Not from one day's work." },
    { cn: "绳锯木断", en: "A rope saws through wood." },
    { cn: "水滴石穿", en: "Water drops pierce stone." },
    { cn: "锲而不舍", en: "Carve without giving up." },
    { cn: "金石可镂", en: "Even metal and stone can be engraved." },
    { cn: "只要功夫深", en: "If you work hard enough." },
    { cn: "铁杵磨成针", en: "An iron pestle can be ground into a needle." },
    { cn: "世上无难事", en: "In the world, nothing is difficult." },
    { cn: "只怕有心人", en: "If you set your mind to it." },
    { cn: "天下无难事", en: "In the world, nothing is difficult." },
    { cn: "唯坚忍二字", en: "Only perseverance." },
];

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = proverbs;
}
