// Chinese Proverbs Collection - 200+ Proverbs with Pinyin
// Categories: wisdom, learning, perseverance, friendship, life

const proverbs = [
    // WISDOM
    { cn: "三思而后行", py: "sān sī ér hòu xíng", en: "Think three times before you act. / Look before you leap.", cat: "wisdom" },
    { cn: "知之为知之，不知为不知", py: "zhī zhī wéi zhī zhī, bù zhī wéi bù zhī", en: "To know what you know and know what you do not know is true knowledge.", cat: "wisdom" },
    { cn: "塞翁失马，焉知非福", py: "sài wēng shī mǎ, yān zhī fēi fú", en: "A loss may turn out to be a gain. / Every cloud has a silver lining.", cat: "wisdom" },
    { cn: "祸兮福之所倚，福兮祸之所伏", py: "huò xī fú zhī suǒ yǐ, fú xī huò zhī suǒ fú", en: "Misfortune leans on fortune; fortune hides in misfortune.", cat: "wisdom" },
    { cn: "满招损，谦受益", py: "mǎn zhāo sǔn, qiān shòu yì", en: "Arrogance brings loss, modesty brings benefit.", cat: "wisdom" },
    { cn: "骄者必败", py: "jiāo zhě bì bài", en: "The proud will surely fall. / Pride comes before a fall.", cat: "wisdom" },
    { cn: "见微知著", py: "jiàn wēi zhī zhù", en: "See the significant in the trivial.", cat: "wisdom" },
    { cn: "举一反三", py: "jǔ yī fǎn sān", en: "Infer three from one. / Draw inferences.", cat: "wisdom" },
    { cn: "触类旁通", py: "chù lèi páng tōng", en: "Understand related categories. / Grasp by analogy.", cat: "wisdom" },
    { cn: "实事求是", py: "shí shì qiú shì", en: "Seek truth from facts.", cat: "wisdom" },
    { cn: "明察秋毫", py: "míng chá qiū háo", en: "See clearly the autumn hair. / Perceptive of details.", cat: "wisdom" },
    { cn: "前车之覆，后车之鉴", py: "qián chē zhī fù, hòu chē zhī jiàn", en: "The overturned cart ahead warns the cart behind.", cat: "wisdom" },
    { cn: "欲速则不达", py: "yù sù zé bù dá", en: "Haste makes waste.", cat: "wisdom" },
    { cn: "瓜熟蒂落", py: "guā shú dì luò", en: "When the melon is ripe, it falls. / Things happen in their own time.", cat: "wisdom" },
    { cn: "水到渠成", py: "shuǐ dào qú chéng", en: "When water comes, the channel forms. / Success comes naturally.", cat: "wisdom" },
    { cn: "物极必反", py: "wù jí bì fǎn", en: "When things reach an extreme, they turn back.", cat: "wisdom" },
    { cn: "否极泰来", py: "pǐ jí tài lái", en: "When misfortune reaches its limit, good fortune comes.", cat: "wisdom" },
    { cn: "乐极生悲", py: "lè jí shēng bēi", en: "Extreme joy gives rise to sorrow.", cat: "wisdom" },
    { cn: "月满则亏", py: "yuè mǎn zé kuī", en: "When the moon is full, it wanes.", cat: "wisdom" },
    { cn: "水满则溢", py: "shuǐ mǎn zé yì", en: "When water is full, it overflows.", cat: "wisdom" },
    { cn: "知己知彼，百战不殆", py: "zhī jǐ zhī bǐ, bǎi zhàn bù dài", en: "Know yourself and know your enemy, and you will never be defeated.", cat: "wisdom" },
    { cn: "耳听为虚，眼见为实", py: "ěr tīng wéi xū, yǎn jiàn wéi shí", en: "What you hear may be false, what you see is true.", cat: "wisdom" },
    { cn: "一言既出，驷马难追", py: "yī yán jì chū, sì mǎ nán zhuī", en: "Once spoken, words cannot be taken back even by a team of four horses.", cat: "wisdom" },
    { cn: "人无远虑，必有近忧", py: "rén wú yuǎn lǜ, bì yǒu jìn yōu", en: "He who does not plan for the future will have immediate worries.", cat: "wisdom" },
    { cn: "种瓜得瓜，种豆得豆", py: "zhòng guā dé guā, zhòng dòu dé dòu", en: "As you sow, so shall you reap.", cat: "wisdom" },
    { cn: "江山易改，本性难移", py: "jiāng shān yì gǎi, běn xìng nán yí", en: "Rivers and mountains are easy to change, but one's nature is hard to change.", cat: "wisdom" },
    { cn: "冰冻三尺，非一日之寒", py: "bīng dòng sān chǐ, fēi yī rì zhī hán", en: "Ice three feet thick is not formed in a single day.", cat: "wisdom" },
    { cn: "不入虎穴，焉得虎子", py: "bù rù hǔ xué, yān dé hǔ zǐ", en: "If you don't enter the tiger's den, how can you catch the tiger's cub?", cat: "wisdom" },
    { cn: "机不可失，时不再来", py: "jī bù kě shī, shí bù zài lái", en: "Opportunity knocks but once.", cat: "wisdom" },
    { cn: "百闻不如一见", py: "bǎi wén bù rú yī jiàn", en: "Hearing something a hundred times is not as good as seeing it once.", cat: "wisdom" },

    // LEARNING
    { cn: "活到老，学到老", py: "huó dào lǎo, xué dào lǎo", en: "Live until old, learn until old. / Never too old to learn.", cat: "learning" },
    { cn: "学而不思则罔", py: "xué ér bù sī zé wǎng", en: "Learning without thinking is labor lost.", cat: "learning" },
    { cn: "温故而知新", py: "wēn gù ér zhī xīn", en: "Review the old to learn the new.", cat: "learning" },
    { cn: "三人行，必有我师", py: "sān rén xíng, bì yǒu wǒ shī", en: "When three walk together, there must be a teacher among them.", cat: "learning" },
    { cn: "敏而好学，不耻下问", py: "mǐn ér hào xué, bù chǐ xià wèn", en: "Quick and eager to learn, not ashamed to ask those below.", cat: "learning" },
    { cn: "学而不厌，诲人不倦", py: "xué ér bù yàn, huì rén bù juàn", en: "Never tired of learning, never weary of teaching.", cat: "learning" },
    { cn: "学而时习之，不亦说乎", py: "xué ér shí xí zhī, bù yì yuè hū", en: "To learn and practice regularly, is that not a joy?", cat: "learning" },
    { cn: "玉不琢，不成器", py: "yù bù zhuó, bù chéng qì", en: "Jade uncarved cannot form a vessel.", cat: "learning" },
    { cn: "人不学，不知义", py: "rén bù xué, bù zhī yì", en: "People without learning do not know righteousness.", cat: "learning" },
    { cn: "读书破万卷", py: "dú shū pò wàn juàn", en: "Read ten thousand volumes.", cat: "learning" },
    { cn: "下笔如有神", py: "xià bǐ rú yǒu shén", en: "Write as if guided by gods.", cat: "learning" },
    { cn: "书山有路勤为径", py: "shū shān yǒu lù qín wéi jìng", en: "In the mountain of books, diligence is the path.", cat: "learning" },
    { cn: "学海无涯苦作舟", py: "xué hǎi wú yá kǔ zuò zhōu", en: "In the endless sea of learning, hardship is the boat.", cat: "learning" },
    { cn: "黑发不知勤学早", py: "hēi fà bù zhī qín xué zǎo", en: "In black hair, one does not know to study early.", cat: "learning" },
    { cn: "白首方悔读书迟", py: "bái shǒu fāng huǐ dú shū chí", en: "With white hair, one regrets starting late.", cat: "learning" },
    { cn: "一日为师，终身为父", py: "yī rì wéi shī, zhōng shēn wéi fù", en: "One day as teacher, lifetime as father.", cat: "learning" },
    { cn: "师父领进门，修行在个人", py: "shī fu lǐng jìn mén, xiū xíng zài gè rén", en: "The master leads you to the door, the rest is up to you.", cat: "learning" },
    { cn: "听君一席话，胜读十年书", py: "tīng jūn yī xí huà, shèng dú shí nián shū", en: "Listening to a wise word is better than reading ten years of books.", cat: "learning" },
    { cn: "问渠那得清如许", py: "wèn qú nà dé qīng rú xǔ", en: "How is the stream so clear?", cat: "learning" },
    { cn: "为有源头活水来", py: "wèi yǒu yuán tóu huó shuǐ lái", en: "Because fresh water flows from its source.", cat: "learning" },
    { cn: "纸上得来终觉浅", py: "zhǐ shàng dé lái zhōng jué qiǎn", en: "Knowledge from books is superficial after all.", cat: "learning" },
    { cn: "绝知此事要躬行", py: "jué zhī cǐ shì yào gōng xíng", en: "To truly know, one must practice.", cat: "learning" },
    { cn: "知易行难", py: "zhī yì xíng nán", en: "Knowing is easy, doing is hard.", cat: "learning" },
    { cn: "知行合一", py: "zhī xíng hé yī", en: "Unity of knowledge and action.", cat: "learning" },

    // PERSEVERANCE
    { cn: "有志者事竟成", py: "yǒu zhì zhě shì jìng chéng", en: "Where there is a will, there is a way.", cat: "perseverance" },
    { cn: "滴水穿石", py: "dī shuǐ chuān shí", en: "Dripping water wears through stone. / Perseverance brings success.", cat: "perseverance" },
    { cn: "水滴石穿", py: "shuǐ dī shí chuān", en: "Water drops pierce stone.", cat: "perseverance" },
    { cn: "绳锯木断", py: "shéng jù mù duàn", en: "A rope saws through wood.", cat: "perseverance" },
    { cn: "锲而不舍", py: "qiè ér bù shě", en: "Carve without giving up.", cat: "perseverance" },
    { cn: "金石可镂", py: "jīn shí kě lòu", en: "Even metal and stone can be engraved.", cat: "perseverance" },
    { cn: "只要功夫深", py: "zhǐ yào gōng fu shēn", en: "If you work hard enough.", cat: "perseverance" },
    { cn: "铁杵磨成针", py: "tiě chǔ mó chéng zhēn", en: "An iron pestle can be ground into a needle.", cat: "perseverance" },
    { cn: "世上无难事", py: "shì shàng wú nán shì", en: "In the world, nothing is difficult.", cat: "perseverance" },
    { cn: "只怕有心人", py: "zhǐ pà yǒu xīn rén", en: "If you put your mind to it.", cat: "perseverance" },
    { cn: "吃得苦中苦", py: "chī dé kǔ zhōng kǔ", en: "Eat the bitterest of the bitter.", cat: "perseverance" },
    { cn: "方为人上人", py: "fāng wéi rén shàng rén", en: "Become the highest of the high.", cat: "perseverance" },
    { cn: "不怕慢，就怕站", py: "bù pà màn, jiù pà zhàn", en: "Fear not slowness, but standing still.", cat: "perseverance" },
    { cn: "宝剑锋从磨砺出", py: "bǎo jiàn fēng cóng mó lì chū", en: "A sharp sword is forged through grinding.", cat: "perseverance" },
    { cn: "梅花香自苦寒来", py: "méi huā xiāng zì kǔ hán lái", en: "Plum blossoms are fragrant from bitter cold.", cat: "perseverance" },
    { cn: "一分耕耘，一分收获", py: "yī fēn gēng yún, yī fēn shōu huò", en: "No pain, no gain.", cat: "perseverance" },
    { cn: "天道酬勤", py: "tiān dào chóu qín", en: "Heaven rewards the diligent.", cat: "perseverance" },
    { cn: "勤能补拙", py: "qín néng bǔ zhuō", en: "Diligence can make up for lack of talent.", cat: "perseverance" },
    { cn: "笨鸟先飞", py: "bèn niǎo xiān fēi", en: "The slow bird starts early.", cat: "perseverance" },
    { cn: "业精于勤，荒于嬉", py: "yè jīng yú qín, huāng yú xī", en: "Excellence comes from diligence, failure from play.", cat: "perseverance" },
    { cn: "千里之行，始于足下", py: "qiān lǐ zhī xíng, shǐ yú zú xià", en: "A journey of a thousand miles begins with a single step.", cat: "perseverance" },
    { cn: "不积跬步，无以至千里", py: "bù jī kuǐ bù, wú yǐ zhì qiān lǐ", en: "No thousand-mile journey happens without tiny steps.", cat: "perseverance" },
    { cn: "精诚所至", py: "jīng chéng suǒ zhì", en: "With complete sincerity.", cat: "perseverance" },
    { cn: "金石为开", py: "jīn shí wéi kāi", en: "Even metal and stone will open.", cat: "perseverance" },
    { cn: "卧薪尝胆", py: "wò xīn cháng dǎn", en: "Sleep on brushwood and taste gall. / Endure hardships.", cat: "perseverance" },
    { cn: "破釜沉舟", py: "pò fǔ chén zhōu", en: "Break the cauldrons and sink the boats. / Burn bridges.", cat: "perseverance" },

    // FRIENDSHIP
    { cn: "海内存知己", py: "hǎi nèi cún zhī jǐ", en: "Within the four seas, all men are brothers.", cat: "friendship" },
    { cn: "天涯若比邻", py: "tiān yá ruò bǐ lín", en: "At the ends of the earth, we are as close as neighbors.", cat: "friendship" },
    { cn: "君子之交淡如水", py: "jūn zǐ zhī jiāo dàn rú shuǐ", en: "The friendship of gentlemen is like water.", cat: "friendship" },
    { cn: "小人之交甘若醴", py: "xiǎo rén zhī jiāo gān ruò lǐ", en: "The friendship of petty men is like sweet wine.", cat: "friendship" },
    { cn: "岁寒知松柏", py: "suì hán zhī sōng bǎi", en: "In cold winter, we know the pine and cypress.", cat: "friendship" },
    { cn: "患难见真情", py: "huàn nàn jiàn zhēn qíng", en: "In adversity, we see true friendship.", cat: "friendship" },
    { cn: "路遥知马力", py: "lù yáo zhī mǎ lì", en: "Over a long distance, we know the horse's strength.", cat: "friendship" },
    { cn: "日久见人心", py: "rì jiǔ jiàn rén xīn", en: "Over a long time, we see the person's heart.", cat: "friendship" },
    { cn: "近朱者赤，近墨者黑", py: "jìn zhū zhě chì, jìn mò zhě hēi", en: "Near vermilion, one turns red; near ink, one turns black.", cat: "friendship" },
    { cn: "酒逢知己千杯少", py: "jiǔ féng zhī jǐ qiān bēi shǎo", en: "With a close friend, a thousand cups are not enough.", cat: "friendship" },
    { cn: "话不投机半句多", py: "huà bù tóu jī bàn jù duō", en: "With a stranger, half a sentence is too much.", cat: "friendship" },
    { cn: "人心齐，泰山移", py: "rén xīn qí, tài shān yí", en: "When hearts unite, Mount Tai moves.", cat: "friendship" },
    { cn: "众人拾柴火焰高", py: "zhòng rén shí chái huǒ yàn gāo", en: "When everyone adds firewood, the flames rise high.", cat: "friendship" },
    { cn: "三个臭皮匠", py: "sān gè chòu pí jiàng", en: "Three cobblers with their wits combined.", cat: "friendship" },
    { cn: "赛过诸葛亮", py: "sài guò zhū gě liàng", en: "Surpass Zhuge Liang.", cat: "friendship" },
    { cn: "单丝不成线", py: "dān sī bù chéng xiàn", en: "A single thread does not make a line.", cat: "friendship" },
    { cn: "独木不成林", py: "dú mù bù chéng lín", en: "A single tree does not make a forest.", cat: "friendship" },
    { cn: "孤掌难鸣", py: "gū zhǎng nán míng", en: "A single palm cannot clap.", cat: "friendship" },
    { cn: "一个好汉三个帮", py: "yī gè hǎo hàn sān gè bāng", en: "A good man needs three helpers.", cat: "friendship" },
    { cn: "远亲不如近邻", py: "yuǎn qīn bù rú jìn lín", en: "A distant relative is not as good as a near neighbor.", cat: "friendship" },

    // LIFE
    { cn: "一寸光阴一寸金", py: "yī cùn guāng yīn yī cùn jīn", en: "An inch of time is an inch of gold. / Time is precious.", cat: "life" },
    { cn: "光阴似箭", py: "guāng yīn sì jiàn", en: "Time flies like an arrow.", cat: "life" },
    { cn: "日月如梭", py: "rì yuè rú suō", en: "The sun and moon shuttle back and forth.", cat: "life" },
    { cn: "少壮不努力", py: "shào zhuàng bù nǔ lì", en: "If one does not work hard in youth.", cat: "life" },
    { cn: "老大徒伤悲", py: "lǎo dà tú shāng bēi", en: "In old age one will grieve in vain.", cat: "life" },
    { cn: "树欲静而风不止", py: "shù yù jìng ér fēng bù zhǐ", en: "The tree wishes to be still, but the wind will not stop.", cat: "life" },
    { cn: "子欲养而亲不待", py: "zǐ yù yǎng ér qīn bù dài", en: "The son wishes to care for parents, but they are gone.", cat: "life" },
    { cn: "人生自古谁无死", py: "rén shēng zì gǔ shuí wú sǐ", en: "Since ancient times, who has not died?", cat: "life" },
    { cn: "留取丹心照汗青", py: "liú qǔ dān xīn zhào hàn qīng", en: "Leave a loyal heart to shine in history.", cat: "life" },
    { cn: "生当作人杰", py: "shēng dāng zuò rén jié", en: "In life, be a hero among men.", cat: "life" },
    { cn: "死亦为鬼雄", py: "sǐ yì wéi guǐ xióng", en: "In death, be a champion among ghosts.", cat: "life" },
    { cn: "人生得意须尽欢", py: "rén shēng dé yì xū jìn huān", en: "In life's prime, enjoy to the fullest.", cat: "life" },
    { cn: "莫使金樽空对月", py: "mò shǐ jīn zūn kōng duì yuè", en: "Do not let the golden cup face the moon in vain.", cat: "life" },
    { cn: "天生我材必有用", py: "tiān shēng wǒ cái bì yǒu yòng", en: "Heaven gave me talents for a purpose.", cat: "life" },
    { cn: "千金散尽还复来", py: "qiān jīn sàn jìn huán fù lái", en: "A thousand gold spent will return again.", cat: "life" },
    { cn: "但愿人长久", py: "dàn yuàn rén cháng jiǔ", en: "May we all be blessed with longevity.", cat: "life" },
    { cn: "千里共婵娟", py: "qiān lǐ gòng chán juān", en: "Though far apart, we are still under the same moon.", cat: "life" },
    { cn: "家和万事兴", py: "jiā hé wàn shì xīng", en: "When the family is harmonious, all affairs prosper.", cat: "life" },
    { cn: "百善孝为先", py: "bǎi shàn xiào wéi xiān", en: "Of all virtues, filial piety comes first.", cat: "life" },
    { cn: "身体发肤，受之父母", py: "shēn tǐ fà fū, shòu zhī fù mǔ", en: "Body, hair and skin are received from parents.", cat: "life" },
    { cn: "父母在，不远游", py: "fù mǔ zài, bù yuǎn yóu", en: "While parents are alive, do not travel far.", cat: "life" },
    { cn: "游必有方", py: "yóu bì yǒu fāng", en: "If you travel, have a destination.", cat: "life" },
    { cn: "三十年河东", py: "sān shí nián hé dōng", en: "Thirty years on the east of the river.", cat: "life" },
    { cn: "三十年河西", py: "sān shí nián hé xī", en: "Thirty years on the west of the river.", cat: "life" },
    { cn: "花无百日红", py: "huā wú bǎi rì hóng", en: "Flowers are not red for a hundred days.", cat: "life" },
    { cn: "人无千日好", py: "rén wú qiān rì hǎo", en: "People are not good for a thousand days.", cat: "life" },
    { cn: "金窝银窝不如自己的狗窝", py: "jīn wō yín wō bù rú zì jǐ de gǒu wō", en: "Gold nest, silver nest, not as good as one's own dog nest.", cat: "life" },

    // INTEGRITY
    { cn: "人而无信，不知其可", py: "rén ér wú xìn, bù zhī qí kě", en: "If a man is not trustworthy, what can he do?", cat: "wisdom" },
    { cn: "一言九鼎", py: "yī yán jiǔ dǐng", en: "One word weighs as much as nine tripods.", cat: "wisdom" },
    { cn: "一诺千金", py: "yī nuò qiān jīn", en: "A promise is worth a thousand gold.", cat: "wisdom" },
    { cn: "言必行，行必果", py: "yán bì xíng, xíng bì guǒ", en: "Words must be acted upon, actions must have results.", cat: "wisdom" },
    { cn: "知耻近乎勇", py: "zhī chǐ jìn hū yǒng", en: "Knowing shame is close to courage.", cat: "wisdom" },
    { cn: "过而能改，善莫大焉", py: "guò ér néng gǎi, shàn mò dà yān", en: "To err and then reform is the greatest good.", cat: "wisdom" },
    { cn: "浪子回头金不换", py: "làng zǐ huí tóu jīn bù huàn", en: "A prodigal son returning is worth more than gold.", cat: "wisdom" },
    { cn: "富贵不能淫", py: "fù guì bù néng yín", en: "Wealth and rank cannot corrupt.", cat: "wisdom" },
    { cn: "贫贱不能移", py: "pín jiàn bù néng yí", en: "Poverty and lowliness cannot shift.", cat: "wisdom" },
    { cn: "威武不能屈", py: "wēi wǔ bù néng qū", en: "Might and force cannot bend.", cat: "wisdom" },
];

// Cantonese Proverbs (粤语谚语)
const cantoneseProverbs = [
    { cn: "十個茶壺九個蓋", py: "sahp go chàh wu gáu go goi", en: "Ten teapots but only nine lids. / Not enough to go around.", cat: "cantonese" },
    { cn: "牛唔飲水唔撳得牛低頭", py: "ngàuh mh yám séui mh gahm dāk ngàuh dài tàuh", en: "You can't force a cow to drink or bow its head. / You can't force someone to do what they don't want.", cat: "cantonese" },
    { cn: "有早知，冇乞兒", py: "yáuh jóu jī, móuh hat yìh", en: "If we knew beforehand, there'd be no beggars. / Hindsight is 20/20.", cat: "cantonese" },
    { cn: "走得和尚走唔到寺", py: "jáu dāk wòh seuhng jáu mh dōu jih", en: "The monk can run but not the temple. / You can't escape responsibility.", cat: "cantonese" },
    { cn: "小時偷針，大時偷金", py: "síu sìh tāu jām, daaih sìh tāu gām", en: "Steal a needle in childhood, steal gold in adulthood. / Bad habits start small.", cat: "cantonese" },
    { cn: "不怕虎生三隻口，只怕人懷兩樣心", py: "bat pa fu saang sāam jek háu, jí pa yàhn wàaih léuhng yeuhng sām", en: "Not afraid of a tiger with three mouths, but a person with two hearts. / Humans are more dangerous than beasts.", cat: "cantonese" },
    { cn: "雞髀打人牙骹軟", py: "gāi bei daa yàhn ngàh hàau yúhn", en: "Chicken legs make people's jaws soft. / Bribery works wonders.", cat: "cantonese" },
    { cn: "一尺之捶，日取其半，萬世不竭", py: "yāt chek jī séuih, yaht chéui kéi bun, maahn sai bat kit", en: "A foot-long stick, cut in half daily, never exhausted. / Infinite divisibility.", cat: "cantonese" },
    { cn: "狗眼看人低", py: "gáu ngáahn hon yàhn dāi", en: "A dog's eye looks down on people. / Snobbish people look down on others.", cat: "cantonese" },
    { cn: "同人唔同命，同遮唔同柄", py: "tùhng yàhn mh tùhng meng, tùhng jē mh tùhng beng", en: "Same person, different fate; same umbrella, different handle. / Same situation, different outcomes.", cat: "cantonese" },
    { cn: "死牛一便頸", py: "séi ngàuh yāt bin géng", en: "A dead cow with a stiff neck. / Stubborn as a mule.", cat: "cantonese" },
    { cn: "食碗面，反碗底", py: "sihk wún mihn, fáan wún dái", en: "Eat from the bowl, then turn it over. / Bite the hand that feeds you.", cat: "cantonese" },
    { cn: "有咁大隻蛤乸隨街跳", py: "yáuh gam daaih jek gap nàah chèuih gāai tiu", en: "Such a big frog won't jump on the street for free. / No such thing as a free lunch.", cat: "cantonese" },
    { cn: "邊有咁大隻蛤乸隨街跳", py: "bīn yáuh gam daaih jek gap nàah chèuih gāai tiu", en: "Where would such a big frog jump on the street? / If it sounds too good to be true, it probably is.", cat: "cantonese" },
    { cn: "皇帝唔急太監急", py: "wòhng dai mh gāp taai gām gāp", en: "The emperor's not worried but the eunuchs are. / More anxious than the person concerned.", cat: "cantonese" },
    { cn: "鹹魚翻生", py: "hàahm yùh fāan sāang", en: "A salted fish comes back to life. / Making an impossible comeback.", cat: "cantonese" },
    { cn: "豬籠入水", py: "jyū lùhng yahp séui", en: "Water enters a bamboo basket. / Money flowing in from all directions.", cat: "cantonese" },
    { cn: "濕水炮仗", py: "sāp séui paau jeung", en: "A wet firecracker. / Useless or won't explode/achieve.", cat: "cantonese" },
    { cn: "鬼拍後尾枕", py: "gwái paak hauh méih jám", en: "A ghost pats the back of your pillow. / Speaking without thinking; blurting out secrets.", cat: "cantonese" },
    { cn: "竹籠打水一場空", py: "juk lùhng daa séui yāt chèuhng hūng", en: "Drawing water with a bamboo basket - all in vain. / Futile effort.", cat: "cantonese" },
    { cn: "醜婦終須見家翁", py: "cháu fuh jūng sēu gin gā yūng", en: "An ugly daughter-in-law must eventually meet her father-in-law. / Can't hide the truth forever.", cat: "cantonese" },
    { cn: "一竹篙打一船人", py: "yāt jūk gōu daa yāt syùhn yàhn", en: "One bamboo pole hits everyone on the boat. / Tar everyone with the same brush.", cat: "cantonese" },
    { cn: "山水有相逢", py: "sāan séui yáuh sēung fùhng", en: "Mountains and waters will meet again. / Our paths will cross again.", cat: "cantonese" },
    { cn: "狗咬狗骨", py: "gáu ngáau gáu gwāt", en: "Dog bites dog bone. / Infighting among crooks.", cat: "cantonese" },
    { cn: "捉到鹿都唔識脫角", py: "jūk dōu lūk dōu mh sīk tyut gok", en: "Caught the deer but don't know how to remove the antlers. / Can't finish what you started.", cat: "cantonese" },
    { cn: "係咁意", py: "haih gam yi", en: "Just a little gesture. / Just a token; casually.", cat: "cantonese" },
    { cn: "走得甩", py: "jáu dāk lät", en: "Able to run away. / Getting away with it.", cat: "cantonese" },
    { cn: "執到寶", py: "jāp dōu bóu", en: "Picked up treasure. / Found a bargain or great deal.", cat: "cantonese" },
    { cn: "走寶", py: "jáu bóu", en: "Missed the treasure. / Missed a good opportunity.", cat: "cantonese" },
    { cn: "踩過界", py: "cháai gwo gaa", en: "Stepped over the boundary. / Overstepped one's bounds.", cat: "cantonese" },
    { cn: "食塞米", py: "sihk choi máih", en: "Ate sticky rice. / Got into trouble; stuck in a mess.", cat: "cantonese" },
];

// Combine all proverbs for display
const allProverbs = [...proverbs, ...cantoneseProverbs];

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { proverbs, cantoneseProverbs, allProverbs };
}
